name: 'Ozone build deploy'
description: 'Builds containers, pushes them to docker repo, deploys on k8s cluster using ozone'
inputs:
  context:
    description: 'Ozone context'
    required: true
  docker_user:
    description: 'Dockerhub username'
    required: true
  docker_pass:
    description: 'Dockerhub password'
    required: true
  docker_registry:
    description: 'Dockerhub password'
    required: true
  domain:
    description: 'Domain'
    required: true
  k8s_secret_base64:
    description: 'Base64 encryption of k8s secret'
    required: true
  k8s_config_base64:
    description: 'Base64 encryption of k8s config'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install deps
      uses: ./.github/actions/install-deps
    - name: "Make kube directory"
      shell: bash
      run: mkdir ~/.kube
    - name: "Setup kubectl config for auth"
      shell: bash
      run: echo "${{ inputs.k8s_config_base64 }}" | base64 --decode > ~/.kube/config
    - name: "Ozone - Build deploy."
      shell: bash
      run: cd $GITHUB_WORKSPACE && ozone r -c ${{ inputs.context }} -d all
      env:
        GIT_BRANCH: ${{ github.head_ref }}
        SECRET_BASE64: ${{ inputs.k8s_secret_base64 }}
        KUBECTL_CONFIG_BASE64: ${{ inputs.k8s_config_base64 }}
        DOCKER_REGISTRY: ${{ inputs.docker_registry }}
        DOCKER_REPO: ${{ inputs.docker_repo }}
        DOMAIN: ${{ inputs.domain }}