name: Pull Request Opened / Committed to
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # token: ${{ secrets.GH_PAT }} # token not needed for opensource repos.
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}
      - name: Set up Go 1.14
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.14
      - name: Build deploy test
        uses: ./.github/actions/build-deploy
        with:
          docker_registry: ${{ env.DOCKER_REGISTRY }}
          domain: ${{ env.DOMAIN }}
          k8s_secret_base64: ${{ secrets.SECRET_BASE64 }}
          k8s_config_base64: ${{ secrets.KUBECTL_CONFIG_BASE64 }}
          context: ${{ env.CONTEXT }}
      - name: Test
        uses: ./.github/actions/postman-health-test
        env:
          GIT_BRANCH: ${{ github.head_ref }}
          DOMAIN: ${{ env.DOMAIN }}
          CONTEXT: ${{ env.CONTEXT }}
    env:
      CONTEXT: dynamic-ns-k8s
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      DOCKER_USER: ozone2021
      DOMAIN: oz0n3.com
      DOCKER_REGISTRY: ozone2021